### ISSUE TITLE
LICENSE needed

### ISSUE THREAD

**Issue by jayvdb** [apljungquist/tox-constraints#1]

**Comment by apljungquist** [comment]
Should do the trick, right?

**Comment by jayvdb** [comment]
Also add to MANIFEST.in , and it would be great if you could add the tests (and test data) and docs to the sdist also.
That makes it easier for me to create an rpm spec for the next release.

**Comment by apljungquist** [comment]
Happy to. Is there a way to tell if all the necessary files have been included?

For instance, I don't understand how the tests will be used, especially if the test runner is not specified somehow, so I cannot tell if they have been properly included.

**Comment by jayvdb** [comment]
ah, a good way is to do `setup.py sdist` , and then go to a new area, unpack the created sdist, and use whatever test runner you wish to run the tests.

A packager can figure out what test runner to use.

In an ideal world, you can set up the test runner in setup.py so that `setup.py test` also works from a clean unpacked sdist.  But if you are using pytest, we can use `pytest-runner` which does all the voodoo so that `setup.py pytest` works, which is good enough.

**Comment by apljungquist** [comment]
The files you request are included in the sdist. In fact, all files that are under source control are included in the sdist due to `setuptools_scm`. But I am guessing your need is that they be explicitly matched in the `MANIFEST.in` file?
