### ISSUE TITLE
Tests rely on Python 3.7 and internet connection to PyPI

### ISSUE THREAD

**Issue by jayvdb** [apljungquist/tox-constraints#3]
It would be nice if the tests could work on the current version of Python used to invoke the test runner.  e.g. on my openSUSE test builds for Tumbleweed, I run the tests on Python 3.8, and on Leap the only Python 3 version is Python 3.6 (or Python 2.7 if that is also possible).  I dont mind if I need to set some environment variable in order to help the test runner.

In addition, but probably a bit harder, is the tests are running on a VM isolated from the internet, and thus cut off from PyPI.  The tests are a sample project, with typical dev tools being used, but those tools dont add much to verify that tox constraints is working correctly.  More specific tests can be created with fictitious packages build and installed during the test sequence.
Another approach is to enable site-packages throughout the test invocation, and generate the requirements files from the versions which are pre-installed.

i.e. I can install `python3-flake8`, and it will be in site-packages, but its version will change over time as the package is upgraded and I cant prevent that.

**Comment by jayvdb** [comment]
Builds with failure logs can be seen at https://build.opensuse.org/package/show/home:jayvdb:tox/python-tox-constraints , but I believe you'll need to create an account there to see the logs, and I think I've explained the possible ways to fix it above so that it isnt important to see the logs.  Happy to explain more if required, or dump logs if preferred..  btw, `test_nothing` passes.

**Comment by apljungquist** [comment]
Based on our previous conversation I assume that this is for the purpose of building and distributing this package (as opposed to  testing a third python package using tax and this tax plugin without internet). Is this correct?

Are you trying to run only the unit tests using `pytest` (as opposed to running all the tests in `tox.ini`)?

**Comment by jayvdb** [comment]
I am attempting to run as many of the tests in this repository as possible in a isolated VM, in order to fail the build of this package whenever some change elsewhere in the ecosystem causes a problem.  The other packages in the distro can not be controlled - the dependencies all change, including tox, pytest, and even Python.  Builds occur against multiple configs concurrently, supporting older stable branches of the OS.  Only `test_nothing` is easy to be run on any config.
